# 异常处理

**异常是程序在执行期间产生的问题**。C++异常是指在程序运行时发生的情况，比如尝试除以零的操作。

**异常处理机制允许程序中独立开发的部分能够在运行时就出现的问题并进行通信并作出相应的处理**。可以将问题的检测与解决过程相分离；程序的一部分负责检测问题的出现，然后另一部分负责解决该问题的任务，用于处理软件或信息系统出现的异常状况。

**为什么要进行异常处理？**

+ 异常处理可以让程序沿一条不会出错的路径继续执行；也可以让程序在异常结束时，但是在结束之前将内存中的数据写入文件、关闭打开的文件、释放动态分配的内存空间等。
+ 一发现异常情况就立即处理不一定妥当，有时需要由函数的调用者决定如何处理更加适合，尤其是库函数是由程序员调用，用以完成与具体应用无关的通用功能的函数，贸然处理未必符合要求。
+ 将异常分散在各处进行处理不利于代码的维护，对不同地方发生的同种异常，都要编写相同的处理代码是一种冗余；将各种异常进行集中处理，程序会容易编写维护。

c++异常处理涉及到三个关键字：**try,catch,throw。**

+ throw:当问题出现时，程序会抛出一个异常；
+ catch:在想要处理问题的地方，通过异常处理程序捕获异常；
+ try:try块中的代码标识将被激活为特定异常，后面通常跟着一个或者多个catch块。

**如果一个块抛出一个异常，捕获异常的方法会使用try和catch关键字**，try块中放置可能抛出异常的代码，**try块中的代码被称为保护代码。**

```apache
try 
{
	// 保护代码
}catch(	ExceptionName e1 )
{
	// catch 块
}catch(	ExceptionName e2 )
{
	// catch 块
}catch(	ExceptionName eN )
{
	// catch 块
}
```

如果try在不同的环境下会抛出不同的异常，这个时候可以尝试罗列多个catch语句，用于捕获不同的异常。

## 抛出异常

可以使用throw语句在代码块任何地方抛出异常，throw语句的操作数可以是任意的表达式，**表达式的结果的类型决定了抛出的异常的类型**。

```
double division(int a, int b)
{
	if(b==0)
		throw "Division by zero condition!"；
	return (a/b);
}
```

## 捕获异常

**catch块跟在try块后面，用于捕获异常，可以指定想要捕获的异常类型，这是有catch关键字后的括号内的异常声明决定的。**

```
try
{
	// 保护代码
}catch( ExceptionName e)
{
	// 处理ExceptionName异常的代码
}
```

上面的代码可以捕获一个类型为ExceptionName的异常，如果想让catch捕获try块抛出的任何类型的异常，则必须在异常声明的括号内使用省略号…,如下所示：

```
try
{
	// 保护代码
}catch(…)
{
	// 能处理任何异常的代码
}
```

## 函数的异常声明列表

为了增强程序的可读性和可维护性，使程序员在使用一个函数时就能够看出这个函数可能会抛出那些异常，c++允许函数在声明和定义时，加上它所能抛出的异常的列表，如下：

`void func() throw (int,double,A,B,C);`

`void func() throw (int,double,A,B,C){...}`

异常声明列表可以在函数声明时写，也可以在函数定义时写。如果两处都写，需要一致。

如果异常声明列表如下编写：

`void func() throw();`

说明函数func()不会抛出任何异常。注：一个函数如果不交待能抛出哪些类型的异常，就可以抛出任何类型的异常。

## C++标准异常

![ExceptionHandling](./异常处理/image/exceptions_in_cpp.png)

| 异常                         | 描述                                                                      |
| ---------------------------- | ------------------------------------------------------------------------- |
| **std::exception**     | 该异常是所有标准 C++ 异常的父类。                                         |
| std::bad_alloc               | 该异常可以通过**new**抛出。                                         |
| std::bad_cast                | 该异常可以通过**dynamic_cast**抛出。                                |
| std::bad_exception           | 这在处理 C++ 程序中无法预期的异常时非常有用。                             |
| std::bad_typeid              | 该异常可以通过**typeid**抛出。                                      |
| **std::logic_error**   | 理论上可以通过读取代码来检测到的异常。                                    |
| std::domain_error            | 当使用了一个无效的数学域时，会抛出该异常。                                |
| std::invalid_argument        | 当使用了无效的参数时，会抛出该异常。                                      |
| std::length_error            | 当创建了太长的 std::string 时，会抛出该异常。                             |
| std::out_of_range            | 该异常可以通过方法抛出，例如 std::vector 和 std::bitset<>::operator[]()。 |
| **std::runtime_error** | 理论上不可以通过读取代码来检测到的异常。                                  |
| std::overflow_error          | 当发生数学上溢时，会抛出该异常。                                          |
| std::range_error             | 当尝试存储超出范围的值时，会抛出该异常。                                  |
| std::underflow_error         | 当发生数学下溢时，会抛出该异常。                                          |
